### ISSUE TITLE
Server url from baseUri option

### ISSUE THREAD

**Issue by hamczu** [cybertk/abao#25]
I wonder if it would be possible to make `server` parameter optional? By default we can get url from baseUri option in RAML file.

**Comment by cybertk** [comment]
It's a good suggestion.

**Comment by MMore** [comment]
+1

**Comment by ProLoser** [comment]
+1

**Comment by plroebuck** [comment]
Played around with this a bit. Bear in mind that the ```baseUri``` setting
in the RAML file is **optional**; it may not be specified at all.

In "abao.js" (corresponding lines in coffeescript source: [abao.coffee](https://github.com/cybertk/abao/blob/master/lib/abao.coffee#L41-L44)),
I added the following:
```javascript
        var url = require('url');         // at top of namespace
        ...
        function(raml, callback) {
          var parsed;
          if (!config.server) {
            if ('baseUri' in raml) {
              parsed = url.parse(raml.baseUri);
              parsed.pathname = parsed.search = parsed.hash = null;
              config.server = url.format(parsed);
            }
          }
          return addTests(raml, tests, callback);
        },
```

It should probably be in its own callback (for maintainability), but I just
piggybacked on the existing callback.

Since my RAML file *does* specify ```baseUri```, I tested by just specifying an
empty string for argv[1] as such:
```bash
$ abao api.raml '' --hookfiles=hooks/*_hooks.js
```

I'm ignoring for now the fact that I got away with using an empty string for a
critical user-provided argument **(and got no error message)**; we should
probably make YA issue for that.

**Comment by ProLoser** [comment]
Just remove this and you should drop the required arg: https://github.com/cybertk/abao/blob/master/bin/abao#L55-L58

**Comment by plroebuck** [comment]
@hamczu, @MMore, @ProLoser, @cybertk 
Could I get you guys to take a look at the beta5 branch and see if this change works for you?
These documentation updates to go with it, but I'd like feedback before going further.

**Comment by ProLoser** [comment]
Yeah this looks awesome

**Comment by plroebuck** [comment]
Anyone else?

**Comment by plroebuck** [comment]
@ProLoser, @cybertk, @martnst, @MMore, @hamczu 

Could you please give the README a final look and see if anything stands out as incorrect?

Is this CoffeeScript function signature correct [here](https://github.com/cybertk/abao/blob/0.4.0-beta.5/README.md#L155)? Everything I've done has used `function(test, done)`; is this alternate interface to validation, or out-of-date documentation?

**Comment by plroebuck** [comment]
Think the changes done thus far are *good enough* to now consider this as official `0.4.0` release.

Would like to migrate to semantic versioning even/odd minor number to denote production/development (i.e., 0.4.0 is production branch, and 0.5.0 will be development branch). Comments?

**Comment by cybertk** [comment]
Looks awesome, +1
