### ISSUE TITLE
No clue how to make abao resolve json references

### ISSUE THREAD

**Issue by snthibaud** [cybertk/abao#47]
I think Abao is very promising, but I cannot get a JSON reference to be resolved. Do you know what I'm doing wrong?

Error: expected value to match json-schema '{"$schema":"http://json-schema...' -> '[{"id":111,"name":"no name","p...'
missing 1 schema: model

A snippet from my raml file looks like:
```
#%RAML 0.8
title: blabla
version: v0.1
baseUri: http://localhost:8000/
schemas:
  - model: !include schemas/model.json
traits:
  - format:
      displayName: format
      queryParameters:
        format:
          example: json

/models:
  is: [format]
  get:
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "array",
                "items": {
                  "$ref": "model"
                }
              }
```
I tried several things for the '$ref' field, but I cannot seem to get it right... Do you have any idea how I should reference my schema? The idea is to specify an array of models.

**Comment by duaiwe** [comment]
I'm encountering the same issue. I poked around to see how this worked, and I'm not sure it'd be very easy, or even possible, for abao to handle this.

Part of the issue is that `raml-parser` does not parse $refs, see this issue: https://github.com/raml-org/raml-js-parser/issues/115 The other part is that while the schema validator abao uses can handle $refs, but it requires the referenced schema to be already loaded, which may not be possible for abao to do dynamically.

One possible workaround *might* be an option to pass in schema files to be pre-loaded. (a `--schemas path/to/schemas/*.json` option, or similar).

**Comment by snthibaud** [comment]
Ok. Thanks for your answer! In the end I just passed complete JSON schema's
to Abao. I still encountered an issue of testing dynamic urls (with a
number in it). That cannot be resolved, can it?


Best regards,

Stéphane

**Comment by pieterA** [comment]
We also needed to be able to use JSON references in our specification for a project.

I actually got it working like duaiwe discribed it. If i deliver a pull request with this functionality (preload schemas from a given path) is there any chance that this pull request will be accepted?

Best regards,
Pieter
